### ISSUE TITLE
Bad Token with Alldebrid

### ISSUE THREAD

**Issue by janaxhell** [rogerfar/rdt-client#147]
**What version are you using?**
2.0.15

**Wat OS are you running?**
OMV6
**Are you using Docker or as a service?**
Docker
**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/8740507/rdtclient.log)

I'm new to this client, so I'm not sure it's a bug, anyway following all the instructions both here and in the settings tips themselves, I cannot grab any torrent from Alldebrid. I have a premium account, I can download them normally with JDownloader, but on docker my chain of Radarr-Prowlarr-rdtclient doesn't work. I have obviously created an Alldebrid APIkey for the client. What happens is this:
I search a movie from Radarr, add it and launch search. Radarr finds it among indexers set on Prowlarr and after a while it appears uploading on Alldebrid. When it's finished I can see it idling on rdtclient flagged as "Bad Token" and after a while it is removed from rdtclient but not from Alldebrid. If I try it again it does the same, much more quick because the file is already there, but still Bad Token. So rdtclient works until the point where it should send the file to Radarr. As Category I chose to use "movies" instead of "radarr" because that's the same I use for qbittorrent and SAB and it just works. For this experiment I have disabled all other cllients and usenet indexers, only torrent trackers and rdtclient are active. Also checking the /download folder nothing appears there while the above happens, so the file does not reach my storage.

**Comment by rogerfar** [comment]
The error comes from the real debrid provider. Are you sure you have alldebrid selected in the settings?

Otherwise try a restart and see if that solves it.
________________________________
From: janaxhell ***@***.***>
Sent: Friday, May 20, 2022 7:47 a.m.
To: rogerfar/rdt-client
Cc: Subscribed
Subject: [rogerfar/rdt-client] Bad Token with Alldebrid (Issue #147)


What version are you using?
2.0.15

Wat OS are you running?
OMV6
Are you using Docker or as a service?
Docker
Please attach a log file here with the log setting set to debug
rdtclient.log<https://github.com/rogerfar/rdt-client/files/8740507/rdtclient.log>

I'm new to this client, so I'm not sure it's a bug, anyway following all the instructions both here and in the settings tips themselves, I cannot grab any torrent from Alldebrid. I have a premium account, I can download them normally with JDownloader, but on docker my chain of Radarr-Prowlarr-rdtclient doesn't work. I have obviously created an Alldebrid APIkey for the client. What happens is this:
I search a movie from Radarr, add it and launch search. Radarr finds it among indexers set on Prowlarr and after a while it appears uploading on Alldebrid. When it's finished I can see it idling on rdtclient flagged as "Bad Token" and after a while it is removed from rdtclient but not from Alldebrid. If I try it again it does the same, much more quick because the file is already there, but still Bad Token. So rdtclient works until the point where it should send the file to Radarr. As Category I chose to use "movies" instead of "radarr" because that's the same I use for qbittorrent and SAB and it just works. For this experiment I have disabled all other cllients and usenet indexers, only torrent trackers and rdtclient are active. Also checking the /download folder nothing appears there while the above happens, so the file does not reach my storage.

**Comment by janaxhell** [comment]
Oh my, yes, restarting worked. I can't believe the oldest trick in computing fixed it. 
FYI, yes, the selected provider was Alldebrid. 
Thanks!
