### ISSUE TITLE
ARM Support ?

### ISSUE THREAD

**Issue by Karamus8rs** [rogerfar/rdt-client#15]
Hi, do you plan to add ARM support to the client ?

Thanks !

**Comment by rogerfar** [comment]
I have added a arm64 (v8) image: https://hub.docker.com/repository/registry-1.docker.io/rogerfar/rdtclient/tags?page=1&ordering=last_updated

Let me know if that works!

**Comment by jschmaltz69** [comment]
I've tried pulling the rogerfar/rdtclient:arm64v8 image on my raspberry pi4 and I can't seem to get the package to spin up at all.  I have tried messing around by running it on the default docker/portainer "bridge" network and on a macvlan that assigns the package an IP address that is more easily accessible on my internal network, but I am not sure if that is the actual issue.

I've been able to get the amd64 package running on my PC's docker environment, so I know that this should work. I'd really like to get this running on my RPi4, however, since I am running other services (sonarr, couchpotato, etc.) on there as well.

Additionally, is there any way you can modify your docker tag to push the correct architecture container on the rogerfar/rdtclient:latest tag? I originally tried pulling that line on my RPi4, and it kept trying to give me the amd64 version. Though I don't really know what I am doing, either.

**Comment by jschmaltz69** [comment]
I suppose log entries would be helpful. This is all it reports at this time:

standard_init_linux.go:219: exec user process caused: exec format error

**Comment by rogerfar** [comment]
Which distro do you use on the pie? I was only able to compile it to 64v8, are you using 64bit os?

**Comment by jschmaltz69** [comment]
It's running openmediavault with the docker implementation available as part of "OMV-Extras"

**Comment by jschmaltz69** [comment]
![image](https://user-images.githubusercontent.com/63426751/105566750-0839ae80-5ceb-11eb-8df7-edd21c9e9637.png)

Maybe this helps? I can dig some more information out of it, if that is of use to you.

**Comment by jschmaltz69** [comment]
After digging into it, I see that the underlying Raspbian builds are all 32-bit kernels, despite the Pi4 having a 64-bit processor, so that would be why I cannot run the container.

**Comment by schardosin** [comment]
I tested on a new Mac Mini with M1 processor, it worked! Thanks!

**Comment by rogerfar** [comment]
That's good to know! I don't really know why the latest tag doesn't show both arches, but for now I will push only amd64 until the client by itself is in a good place, then I'll have a look into compiling armv7.

**Comment by schardosin** [comment]
Sounds good! arm support will be really good with all the macbooks now coming with M1 processor, and the new surface pro X, which are arm based.

**Comment by jschmaltz69** [comment]
Thanks for the follow up. I think your client would be a useful addition to the linuxserver.io fleet as well, though I don't know the process they follow to add new packages.

**Comment by rogerfar** [comment]
If anyone is interested I attempted to do a armv7 (32bit) compile and pushed it to docker, but I have no way of testing it, so if anyone can test it and let me know if there are issues, thanks!

**Comment by jschmaltz69** [comment]
I got it fired up on a RPi4 running on the Docker/Portainer environment within OpenMediaVault. CPU usage is pretty high (~65%) when downloading, but that's not surprising given the device it's running on. I'll report back with any issues should I find something. Thanks for putting this together.

**Comment by jschmaltz69** [comment]
After some testing, I can get radarr and sonarr to initiate downloads, but the rdtclient writes files to my downloads folder as the root user, and that results in a situation where radarr/sonarr cannot move the downloaded files around unless I reset the permissions on the download folder, since they are not running as root users for file operations. 

Would you be willing to add a PID/GID override option for the client's file operations, as per [https://stackoverflow.com/questions/32397496/docker-replicate-uid-gid-in-container-from-host](https://stackoverflow.com/questions/32397496/docker-replicate-uid-gid-in-container-from-host)? Then the desired UID/GID can be passed through as an environment variable. At least, I think that's how that works.

**Comment by timcoop3r** [comment]
> Would you be willing to add a UID/GID override option for the client's file operations, as per https://stackoverflow.com/questions/32397496/docker-replicate-uid-gid-in-container-from-host? Then the desired UID/GID can be passed through as an environment variable. At least, I think that's how that works.

+1 on this, this is what I meant before when I said about running as another user in the container somehow in one of my other issues. The sonaar/radaar linuxserver.io containers (I think all the linuxserver.io containers) do something like this, so seems like the way it normally is done for us linux users. Just wish I understood it better to help out here. :)

**Comment by rogerfar** [comment]
I'm not very familiar with the whole docker ecosystem, but for what I can tell is that all docker containers on a host share the same UID/GID list correct? 

What happens if you run the container with the user switch:
```
docker run --cap-add=NET_ADMIN -d \
              -v /your/download/path/:/data/downloads \
              -v /your/storage/path/:/data/db \
              --log-driver json-file \
              --log-opt max-size=10m \
              --user 1000:1000
              -p 6500:6500 \
              rogerfar/rdtclient
```

**Comment by jschmaltz69** [comment]
I've been playing with this a little bit, and I think each docker container maintains it's own user/group database by default. I think I would have to rebuild the docker image myself and include the desired UID/GID in the build file to allow the container to "operate" as that user. If I try to force the rdtclient to run as the correct "file operations user" on my system (which happens to be UID1001, for example), Docker/Portainer throws an error that implies that this user does not exist in the container, which would make sense, since I am just using your unmodified docker container. I think this is why the LinuxServer packages utilize the UID/GID "workaround" process. 

I ended up browsing around this page about docker user permissions: [https://jtreminio.com/blog/running-docker-containers-as-current-host-user/#ok-so-what-actually-works](url) A lot of it is admittedly over my head, but it also talks about the procedure to conditionally "passthrough" a UID/GID for use by the container when it writes to files.

**Comment by timcoop3r** [comment]
fwiw, I can run as a non-privillege user right now with the docker --user option and don't get any errors and it seems to work fine. Although I did have errors in the past and can't do this with other containers. (e.g. radarr/sonarr)

**Comment by rogerfar** [comment]
I have changed the dockerfile to not run as root but as user 1000 "dotnet". 

I am not sure if that is sufficient, and it might break your existing database file due to a permission issue.

**Comment by jschmaltz69** [comment]
I tried playing around with this, and it blows up a little bit if you don't have the same user configured on the "host" system with the proper permissions:

[04:56:28 ERR] An error occurred using the connection to database 'main' on server '/data/db/rdtclient.db'.,
[04:56:28 FTL] Host terminated unexpectedly,
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.,
 ---> System.IO.IOException: Permission denied,
2021-02-12T04:56:36.8061502Z Caught exception while emitting to sink Serilog.Core.Sinks.RestrictedSink: System.UnauthorizedAccessException: Access to the path '/data/db/rdtclient.log' is denied.

**Comment by jschmaltz69** [comment]
I did reset the permissions on my config folder before running this new test on a "fresh" setup.

**Comment by jschmaltz69** [comment]
Would it be possible to implement something like Solution 3 on [https://dev.to/acro5piano/specifying-user-and-group-in-docker-i2e](https://dev.to/acro5piano/specifying-user-and-group-in-docker-i2e)? I looked into how the LinuxServer images address this issue, and while it's mostly over my head, they use [this code](https://github.com/linuxserver/docker-baseimage-ubuntu/blob/bionic/root/etc/cont-init.d/10-adduser) to set up the environment variables and file permissions, and then they use [s6-setuidgid](https://skarnet.org/software/s6/s6-setuidgid.html) when the package runs (see [here](https://github.com/linuxserver/docker-sonarr/blob/master/root/etc/services.d/sonarr/run)) to apply these settings to the container. Again, I think that's how that works, but I'm not certain on the exact implementation.

**Comment by timcoop3r** [comment]
@jschmaltz69 whats your actual docker run or docker-compose config look like? Setting the user that runs the container should be working. Based on this link, https://docs.linuxserver.io/general/understanding-puid-and-pgid, the linuxserver.io images are compatible with docker version that dont support the user setting, which is why they have this UUID GID feature.

Using the user option and setting a user and group thats present on your system should solve your problem?

e.g I have a system user 'fred' with uid:gid 1003 and I run rdt-client a 'fred' in docker. All the files created by rdt-client are owned by fred and it can access the config db owned by fred?

docker-compose example:

```yaml
version: '2.1'
services:
  rdtc:
    container_name: rdtc
    image: rogerfar/rdtclient
    restart: unless-stopped
    user: 1003:1003
    environment:
      TZ: Europe/London
    volumes:
      - /path/to/downloads:/data/downloads
      - /path/to/config:/data/db
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - "6500:6500"
    network_mode: bridge
```

fred is also the user I use for Plex and for radarr/sonarr/lidarr with their linuxserver.io environment variables, e.g:

```yaml
  sonarr:
    image: ghcr.io/linuxserver/sonarr:preview
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1003
      - PGID=1003
      - UMASK_SET=022
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
      - /path/to/downloads:/data
```

**Comment by jschmaltz69** [comment]
@timcoop3r Thanks for this. I was able to get things working based on your docker-compose file. I got the package to spin up using the terminal/docker-compose up. Part of my problem was that I'm still a Docker noob and I like using Portainer to have a GUI "crutch" to make things a bit easier, and I was not clear on how to implement the `user` option in Portainer. Turns out all you have to do is enter `(UID):(GID)` in the "User" field in the "Command & Logging" options in Portainer when configuring the package (and make sure you are using the right GID; I was using the wrong one, haha). Perhaps this information might help someone down the line. I am using Docker `5:20.10.2~3-0~debian-buster` on a Raspberry Pi4 running OpenMediaVault 5.5.23-1 running the latest version of rdtclient (1.5.5 as of writing).

One thing I noticed, however, is that your docker-compose file does not include the `NET_ADMIN` capability, and the docker-compose on the main page omits this as well, while the docker-run entry specifies that capability. @rogerfar is `NET_ADMIN` still needed for the client? It seems to be running okay for me without it, at this time.

**Comment by rogerfar** [comment]
No I don't think you need `NET_ADMIN`. I copied it over from another docker contain which had a VPN client built in, so I suppose that one needs it.

**Comment by rogerfar** [comment]
I'm going to close this issue for now, if there are any ARM issues either re-open this issue or create a new one.
