### ISSUE TITLE
Rdt-client creates files as read only

### ISSUE THREAD

**Issue by chest069** [rogerfar/rdt-client#161]
Hello,

I just started using UNRAID and decided to use this with Docker in my UNRAID setup. I previously used it in my Windows Docker and liked it but I have run into an issue.

I used your Docker compose file like before but now when things download they are downloading then they are being put into read only folders and because of that Sonarr and Radarr and other programs are unable to move the new data to where it belongs.

Is there something that I need to change with my rdt-client Docker compose file so that I can get this to work with UNRAID? I have tried everything I can think of with no luck.

Please help. Thanks.

**Comment by rogerfar** [comment]
What is there to fix exactly? 

It's all in the readme: https://github.com/rogerfar/rdt-client/blob/master/README-DOCKER.md

**Comment by nwithan8** [comment]
@chest069 @NR2014 If you're using Unraid like I am, you probably want to set the PGID and PUID in your configuration settings for this Docker file. I used PUID 99 and PGID 100 since it's the same as my Sonarr/Radarr and torrent clients, YMMV.

<img width="559" alt="image" src="https://user-images.githubusercontent.com/17054780/177677337-8649fee8-1438-4b65-b2a2-83652f71c972.png">
