### ISSUE TITLE
Disable automatic download function.

### ISSUE THREAD

**Issue by TheWizard67** [rogerfar/rdt-client#183]
I would love to be able to turn off the download feature, and just use it as a gateway for Radarr and Sonarr to interact with RD. Is it possible to do so?

**Comment by krishne35** [comment]
+1 
So that we can use radarr sonarr to create a library on rd

**Comment by rogerfar** [comment]
I have added a new setting called "Post Torrent Download Action". This can be set to "Don't download any files to host".

When this is set, it will not download any of the torrent files from Real Debrid to your host, just make sure that the "Post Download Action" is set to "Remove Torrent From Client" otherwise it will just delete it from Real Debrid right away.
