### ISSUE TITLE
Feature Request: Add to Real Debrid

### ISSUE THREAD

**Issue by berot3** [rogerfar/rdt-client#232]
Hi @rogerfar ,

Thank you so much for this interesting solution. I was wondering if the following szenerio could be realized:

Right now I am running **plex/Jellyfin**. As source for the media I use **rclone** which mounts the **webdav** of Real Debrid (RD). I followed mostly the guide from https://github.com/itsToggle/plex_debrid.

Instead of plex_debrid I would love to use **Sonarr/Radarr**. Then I discovered your wonderful work.
So I'm wondering if it would be possible to simply **"add" the torrents to RD**. This would allow the torrents to available in webdav. Sonarr could then tell plex to update the media library.

Where have I seen this "add torrent to RD"-functionality, you may ask? Stremio, Wako with Helios-addon and plex_debrid is using it.

---

Looking at the other issues, I found these related: 

- #76, which also wanted to have the media **streamed** instead of downloaded. But I don't think .strm-files is the best approach.
 
- #217 is mentioning rclone, which could also lead to an answer for my issue. I hope you can help us both out :)

- Then there is #185, which suggests to "download with rclone". I'm not sure what he meant. But maybe you could check if RD (API) is reporting this back? This would be a key-element I guess.

Thanks again for everything 👍

**Comment by jagvirdehal** [comment]
You can add torrents to RD using the qbittorrent API. Just be sure to set it so that it doesn't download the files to the host afterwards.

The issue with this however is that it does not report the torrent as downloaded in Sonarr/Radarr as I mentioned in #217. This is likely because the files aren't actually present where sonarr/radarr expects them to be.

Potentially could be fixed by configuring sonarr/radarr to look at the rclone mount for the downloaded files, I didn't think of this till now.

Regardless you should still be able to add the torrents to the cloud, I got that part working fine.

**Comment by berot3** [comment]
Thanks a alot @jagvirdehal !

There isn't maybe a guide/wiki that describes how to do this? :)
But if you say it works, I will give it a try. If I have any questions, I'll come back here, ok? :D

**Comment by jagvirdehal** [comment]
@berot3 No problem! And yea, feel free to ask anything here, I'll help ya out best I can.

I didn't follow a guide or anything for this particular thing, but I can give you a quick summary of the steps I took and where to look in case u get stuck:

1. Set up Sonarr/Radarr as you would normally, following the standard guides that are out there. The only thing you want to do differently is adding the download client. I'll get to that.
2. Once you've set them up, you wanna set up RDT Client. Note the username/password you use on the first run, as this is what you will use to connect the apps.
3. Now, you want to look in the qbittorrent section of the RDT settings, and set it so that it doesn't download files to the host (the issue that I have found with this is that Sonarr/radarr will complain that they cannot find the file.)
4. Set up a qbittorrent download client in sonarr/radarr, and use the credentials and port number from RDT wherever it asks.
5. Done! Sonarr/radarr should be able to add torrents to your RD cloud now.

Note: By not downloading the files to the host, you will run into issues when the download is complete, particularly it'll say something like qbittorrent is reporting an error. This is where I got stuck, but there might be a fix for this. Try setting the "Mapped download path" in RDT settings to your WebDAV mount. This path will then be reported to Sonarr/Radarr and show them the download has actually completed. I'm not 100% sure this will work, but its worth a try.

If you get stuck anywhere, or if I wasnt clear about a step just let me know.

Cheers!

**Comment by jagvirdehal** [comment]
Yep, that's the issue I've been running into with #217. I thought it was an RDT issue since Sonarr complains about a qbitTorrent error, but it's probably because it can't find the files. The solution I came up with is to get sonarr to check the rclone mount for the final download, but I haven't tested it since I switched back to plex_debrid. I'll give it another shot when I get the chance.

**Comment by tampas** [comment]
I'm trying to archive the same setup described here.
Despite of not being reported as downloaded to *arr apps i'm trying to symlink the rclone mount files, to another folder for processing with arr apps or with filebot prior to import on Plex without success so far. With this kind of setup i'm trying to circumvent the limitation of read only on the realdebrid mount and adding the metadata files and subtitles local, despite of the actual movie file being a symlink to a remote share. Any upgrades?

**Comment by rogerfar** [comment]
Honestly this goes over my head, what exactly needs to be changed?

**Comment by jagvirdehal** [comment]
@rogerfar TL;DR: Not an issue with rdt client, so there's nothing to change.

If you set it so that it doesn't download the files and just puts it on the cloud, the qbittorrent api in rdt client doesn't appear to report the torrent being completed to Sonarr/Radarr. Looking into it more, it seems like it's an issue with Sonarr/Radarr not finding the files after they're reported as complete. Best workaround is using an rclone mount (such as rclone_rd from itstoggle) and having Sonarr/Radarr look there for completed torrents.

**Comment by rogerfar** [comment]
Yeah that's what is my thought. You can rclone, but if you have a direct path to the files, you can use the mapping in rdt:
![image](https://github.com/rogerfar/rdt-client/assets/1142915/0f04dc2a-9967-496e-b51c-2638e669b4b0)
It will then pretend the file is somewhere else than the actual download path.

And together with this setting:
![image](https://github.com/rogerfar/rdt-client/assets/1142915/d4b3d95e-bb90-43cd-b940-a87d4a19de5e)
Then it won't download the files to your host.

**Comment by mateuszzadorski** [comment]
@jagvirdehal were you able to test this solution out somehow? 

I'm currently testing the plex_debrid solution and while it works great there doesn't seem to be any good solution for the subtitles - only one that requires plex pass webhooks & you still have to jump through hoops of setting rclone union to save srt's 'next' to the RD files.

What you're describing paired with Sonarr + Bazarr seems like a perfect way to achieve that but I'm not sure if I'm getting this right. Ultimately the idea is to trick the Sonarr into believing the file is somehow stored locally while in fact it's only sort of a symlimk pointing to RD cloud location? Would that be somehow mountable in Plex? I'm willing to test out a bit and share my exp. but I'm worried I'm getting stuff mixed up here.

**Comment by jagvirdehal** [comment]
@mateuszzadorski I did actually test it out recently, unfortunately doesn't work. You can get it to download and add it to your RD cloud, but radarr will complain about the files being missing regardless of the fact that it should see them.

Not sure if it's a rdtclient issue tho, I'm guessing it's not expected on the radarr side for the download to finish instantly, so it causes problems. Not really sure though, I didn't take any logs.

**Comment by mateuszzadorski** [comment]
Too bad. Think I'll explore the plex_debrid route a bit more then as ultimately that's tailored more to what I'm after. Thanks for prompt response though mate, saved me some time. As you say it's rather Radarr issue, so gonna stop spamming in here :)

**Comment by dutoural** [comment]
Hey @jagvirdehal did u explore the question further ? I'm trying to replicate the exact same setup :)

**Comment by jagvirdehal** [comment]
@dutoural plex_debrid is probably your best bet, Radarr just doesn't recognize the downloads unless they're actually present on the machine. It'll add it to your real debrid but it'll see the downloads as missing

**Comment by dutoural** [comment]
Yeah I did that. I really like plex_debrid for movies but it is scrappy with shows and especially animes

**Comment by rogerfar** [comment]
Does this answer this problem? https://github.com/rogerfar/rdt-client/issues/299

**Comment by jagvirdehal** [comment]
From what I see in the thread yes! Will try this out sometime

**Comment by bequbed** [comment]
@jagvirdehal could you please perhaps guide me on how I can set it up on my end with Symmlink optiom?

**Comment by bequbed** [comment]
@jagvirdehal could you please perhaps guide me on how I can set it up on my end with Symmlink option? 
Or anyone in general give me brief steps on how i can setup symmlink on my local Windows Server? 
I have a rclone mount for RD under D:\torrents and on rdt client i have used that under rclone mount. 
What should be the mapping on mapped path on rdt client? And what about sonarr? Do i also need setup remote and local path on Sonarr?

**Comment by bequbed** [comment]
Anyone got this to work on Windows? I would really appreciate some help on how to set it up.

**Comment by rogerfar** [comment]
I'm going to close this issue, if you still have specific issues please open a new topic. Also, if someone could write up something for the readme, that would be appreciated!
