### ISSUE TITLE
"Not a valid alpine path error" in Radarr

### ISSUE THREAD

**Issue by Abheek10** [rogerfar/rdt-client#292]
**What version are you using?**
v2.0.32

**Wat OS are you running?**
Windows 11 Education

**Are you using Docker or as a service?**
Docker

**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/12345323/rdtclient.log)

Radarr & RDT client docker images:
![image](https://github.com/rogerfar/rdt-client/assets/32678150/6040813d-4e26-4c33-a373-b925c60c70aa)

I am getting the below error:
![image](https://github.com/rogerfar/rdt-client/assets/32678150/d3bce1df-8db6-4c93-aa7f-c91ab0226d79)

**Comment by kungfoolfighting** [comment]
rdt-client will send the download path where it puts its downloads back to radarr after the successful download.
This path needs to be a path where radarr can find the files inside its own container.
Since you might have different volume mount points in these two containers, rdt-client has an options in the settings called "Mapped Path":
![image](https://github.com/rogerfar/rdt-client/assets/17553106/fb041a5d-2e2e-489f-b4f0-bb57a44871e6)
This should be set to the directory where Radarr will find the files inside its own container.
