### ISSUE TITLE
Folder Structure is broken for Real-Debrid

### ISSUE THREAD

**Issue by rbertwang1** [rogerfar/rdt-client#399]
**What version are you using?**
**2.0.58**

**Wat OS are you running?**
**Unraid 6.12.6**

**Are you using Docker or as a service?**
**Docker**

**Which debrid provider are you using?**
**Real-Debrid**

**Which downloader are you using?**
**Internal Downloader**

Folder hierarchy/structure doesn't seem to be preserved. When adding a torrent/magnet it shows the structure of the files, but when all files are done downloading, it just spits it out into one single folder

![image](https://github.com/rogerfar/rdt-client/assets/156950754/e945e71c-227f-46fd-9285-456b8f7d1d8e)
![image](https://github.com/rogerfar/rdt-client/assets/156950754/7ffe4fab-cc92-4eb1-b408-92bd29211345)

**Comment by rogerfar** [comment]
I had never noticed that, not super easy because a download link isn't connected to a file, so now I'm doing fuzzy matching to see if we can figure out the path.

**Comment by cchance27** [comment]
While this looks annoying and is technically a bug, can't you just use your next step to resort it into folders?, For instance when sonarr moves a movie from download directory it can be told to use season paths.

**Comment by rogerfar** [comment]
This should be fixed in the latest version, please verify or else post a log with a demo torrent.

**Comment by Sculas** [comment]
I'm currently encountering this issue as well on version [v2.0.92](https://github.com/rogerfar/rdt-client/releases/tag/v2.0.92), using AllDebrid and torrent `<nyaa dot si>/view/1350495`.

---

This is the folder structure according to the tracker, and is also what I expect to see:

![image](https://github.com/user-attachments/assets/4af2f38e-153b-41cd-8783-e19bde5b44bb)

However, this is the folder structure I see in `rdt-client` and is also what I see on disk:

![image](https://github.com/user-attachments/assets/81f0627f-1f91-4f7c-8c70-4f405fa7d6b2)

It's all put into a single folder instead of folders as it should. In case it helps in figuring out the issue,
this torrent was cached by AllDebrid, so that may affect the way AllDebrid returns the file structure to `rdt-client`.
