### ISSUE TITLE
Add support for alldebrid

### ISSUE THREAD

**Issue by ravensorb** [rogerfar/rdt-client#44]
Any thought on adding support for some of the additional services out there like https://alldebrid.com/

**Comment by rogerfar** [comment]
Yeah doesn't look too hard, I can make another library that implements the alldebrid API.

**Comment by Lioon2** [comment]
I support this ! Would love to have your tool with alldebrid

**Comment by serialpotato** [comment]
Really eager to see how this unfolds

**Comment by ShawnAsap** [comment]
Alldebrid support would be great... especially when Real debrid goes down. Also Premiumize. Looking forward to it. Thanks!

**Comment by rogerfar** [comment]
Took a while, but I added first support for AllDebrid.

It works the same as RealDebrid, except, you can't select files when adding a torrent manually. This is because AllDebrid always downloads the full torrent. Only when the torrent is added the file list becomes visible. Even then, I found that some files will be grouped in 1 download link, so even then it's hard to figure it out.

It will use the "Only download files over X size" setting, but it will only check the actual download link.

If anyone find any bugs, please open a new ticket :)

**Comment by ravensorb** [comment]
Looking good so far!  Question, are you planning to update the strings in the UI to indicate support for both (ex: settings dialog)?

**Comment by rogerfar** [comment]
I haven't gone very thoroughly through the project, but if you have specific examples please let me know and I'll fix them.
