### ISSUE TITLE
Video file filter

### ISSUE THREAD

**Issue by vellencw** [rogerfar/rdt-client#6]
Just started using this app, and love it so far!

Do you have any plans to allow only adding the video files from a torrent instead of the whole folder?  I'd like to be able to stream stuff directly from RD's servers, but can't if it downloads the whole folder and zips it.  Hopefully this feature would be easy to add, since the RD website pretty much already does that by default.  It would also probably greatly increase the number of torrents that are already cached.

Additionally, a way to have a default setting of not downloading to the host would be amazing as well, instead of having to click the box every time.  I guess maybe just not setting a download location would probably take care of it.

Thanks so much for your work!

**Comment by rogerfar** [comment]
I actually had a feature in there at one point to skip those small files, but I found it also excluded SRT files but kept including samples. I can have a look at putting it in again, maybe just a bit smarter.

**Comment by timcoop3r** [comment]
Another thing to consider with this feature is the doubling of write wear on consumer grade SSD. When downloading very large files there is considerable additional wear caused because of the way Real Debrid package these as RAR. Not the fault of rdt-client of course, but could be frustrating none the less. Being able to avoid the RAR behaviour by selecting only the main files would be advantageous, especially when automatically added with something like Radarr.

**Comment by rogerfar** [comment]
I have added a simple file filter option where you can specify the minimum file size when it selects file.

Now I did find that it's a bit unreliable. If RealDebrid already has that torrent, it will skip file selection and give you the full torrent right away, forcing you to basically download the whole thing.

**Comment by rogerfar** [comment]
I have tested this a few times now with not cached torrents and it seems to work!
