### ISSUE TITLE
torbox downloads fail

### ISSUE THREAD

**Issue by dragged9698** [rogerfar/rdt-client#618]
**What version are you using?**
latest
**Wat OS are you running?**
ubuntu
**Are you using Docker or as a service?**
docker
**Which debrid provider are you using?**
torbox
**Which downloader are you using?**
symlink

I am unsure if this is related to current server issues with torbox, I'm led to believe that it is since there are no issues related to downloads not working with torbox since the update 5 days ago, but currently i am completely unable to get any downloads to work through torbox. 

[10:13:21 ERR] Download reported an error: The value cannot be an empty string. (Parameter 'oldValue') for download 51783603-fe1f-484b-abcf-88ea25356e46. Completed: 0%, avg speed: 0bytes/s (4d5a575c-7ca9-4e64-9f29-fbb82b429def) remoteID:  for torrent [SubsPlus+] 2.5 Dimensional Seduction - S01E21 (AMZN WEB 1080p AVC AAC) | 2.5 Jigen no Ririsa (2bfdec50dc3316f9e1d02b28e9cfe740d2b3a6e1 - cached 100%) (64ebc440-83f5-4887-860f-82a0bb410157)

**Comment by alankeny** [comment]
**What version are you using?**
v2.0.87

**What OS are you running?**
Debian 12 Bookworm

**Are you using Docker or as a service?**
Service

**Which debrid provider are you using?**
Torbox

**Which downloader are you using?**
Internal

**Please attach a log file here with the log setting set to debug**
Full debug log posted at [this gist](https://gist.github.com/alankeny/3d3fe845bc8a48c51b417d56f7ef5442).

I was using v2.0.86 with Real-Debrid successfully until yesterday.  I upgraded to v2.0.87 and switched providers to Torbox.  It looks like a similar issue to the one @dragged9698 reported, but the null parameter in the error is different.  The first few errors reported are:

    [ERR] RdtClient.Service.BackgroundServices.TaskRunner: Unexpected error occurred in ProviderUpdater: Value cannot be null. (Parameter 'source')

    [ERR] RdtClient.Service.Services.Downloaders.InternalDownloader: Unable to retrieve content size before downloading, received response: MethodNotAllowed

I don't believe this is related to the current Torbox issues, because I was able to use the unredacted form of the URL from the debug log to successfully download the ZIP file from Torbox.

**Comment by alankeny** [comment]
I've multiplied the values of Download Client > Connection Timeout and Provider > Connection Timeout by 100.  I'm still getting an empty directory with no file downloaded.  The following error is repeated in the log until I delete the torrent:

    [ERR] RdtClient.Service.BackgroundServices.TaskRunner: Unexpected error occurred in ProviderUpdater: Value cannot be null. (Parameter 'source')

If instead I copy the storage-zip.torbox.app download link from the torrent, run `curl -O -J -L` on it from the empty directory, and then unzip the downloaded file manually, everything completes successfully.

Let me know if there's another connection timeout setting I need to change.  Thanks!

**Comment by asylumexp** [comment]
My mistake on that one, thought it was an issue with timeouts that someone else was having that looked similar at a quick glance to what you said. Although i still believe this is an issue with TorBox, as before the surge of users on TorBox people were able to download using RDT no issue, so id say wait until Monday and see if it changes.

**Comment by Amcro** [comment]
I'm having the same issue, with different error log

[15:55:34 ERR] Unable to retrieve content size before downloading, received response: MethodNotAllowed 
System.Exception: Unable to retrieve content size before downloading, received response: MethodNotAllowed 
[15:55:34 ERR] Unable to start download: An unexpected error occurred preparing download *censored URL* for torrent Knives Out (2019) [1080p] [BluRay] [5.1] [YTS] [YIFY]: Unable to retrieve content size before downloading, received response: MethodNotAllowed  for download f95560d4-7db9-4307-bf88-3f25614d26db. Completed: 0%, avg speed: 0bytes/s (d15ccca0-e37d-4448-b2cf-955d276ee4d6) remoteID:  for torrent Knives Out (2019) [1080p] [BluRay] [5.1] [YTS] [YIFY] (3b2694fb0e0bb41d7fb92c79d7d0cc7b90543a13 - cached 100%) (563998c6-21cb-4d0b-aed0-29f49837f9c8)

It seems that TorBox is giving ZIP links instead of links to download files individually. I have set RDT client to download only files larger than 3MB and not to download txt,jpg,png files but it looks like it's still trying to download all files at once in zip file. 
My guess is we still need to wait until TorBox fixes/upgrades servers.

**Comment by asylumexp** [comment]
That’s intended functionality atm. I wanted a working PR before I went away for a while so I opted for it to all be downloaded in zip with the zip setting removed. This will be changed when I can do work again. Although I didn’t pickup the MethodNotAllowed errors, they don’t affect functionality.

**Comment by Amcro** [comment]
So that means i need to manually do extract? This kills the automation with radarr and sonarr integrations right?

**Comment by asylumexp** [comment]
> So that means i need to manually do extract? This kills the automation with radarr and sonarr integrations right?

When you open the download folder do you see a file with a [uuid for a name, with no extension](https://github.com/rogerfar/rdt-client/issues/616) or a zip file that is unextracted.

**Comment by saiyogi2k** [comment]
Hello, Even i am experiencing some issues with TorBox and RDT. RDT says finished but when go to the download location it just creates an empty folder in the torrent's name. Ig today TorBox updated their servers but i am still having this issue.

**Comment by saiyogi2k** [comment]
Recent logs for the following:
https://pastebin.com/s73Lcvqs

> Hello, Even i am experiencing some issues with TorBox and RDT. RDT says finished but when go to the download location it just creates an empty folder in the torrent's name. Ig today TorBox updated their servers but i am still having this issue.

**Comment by asylumexp** [comment]
I haven’t been able to replicate this myself. I’m doing this all from a phone which just takes too long to be able to test stuff and figure out what’s wrong. ill try fix it in a couple weeks, if it isn’t already fixed.

**Comment by AlbanVidalenche** [comment]
Hi, i get the same issue as @Amcro 
`2024-11-25
23:35:00.972 +00:00 [ERR] RdtClient. Service Services. Downloaders. InternalDownloader: Unable to retrieve content size before downloading, received response: MethodNotAllowed
System. Exception: Unable to retrieve content size before downloading,
received
response: MethodNotAllowed
2024-11-25
23: 35:00.984
+00:00 [ERR] RdtClient. Service. Services. TorrentRunner: Unable to start download:
`

**Comment by dragged9698** [comment]
> Recent logs for the following: https://pastebin.com/s73Lcvqs
> 
> > Hello, Even i am experiencing some issues with TorBox and RDT. RDT says finished but when go to the download location it just creates an empty folder in the torrent's name. Ig today TorBox updated their servers but i am still having this issue.

Torbox has yet to receive their new servers, just fyi.
![image](https://github.com/user-attachments/assets/e2dc17ce-8ac9-42dc-9c95-c388a86de76f)

**Comment by Amcro** [comment]
Can confirm, with new servers still same issue. RDTC can see all files, grabs the zip link and doesn't download anything. It only creates folder without files.

![image](https://github.com/user-attachments/assets/e5133140-0977-4489-b29e-0e3db61aae29)

Not usable at all with TorBox.

**Comment by asylumexp** [comment]
Although #625 should fix the errors being encountered here, TorBox won't be useable with RDTClient due to #616.
